"""02 -Field respon on table Contact created

Revision ID: 7d523ce8d5b3
Revises: 58bbc6f99b7a
Create Date: 2024-11-16 14:14:47.833809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d523ce8d5b3'
down_revision = '58bbc6f99b7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respon', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_column('respon')

    # ### end Alembic commands ###
