# Generated by Django 5.0 on 2024-01-17 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="variacao",
            options={"verbose_name": "Variação", "verbose_name_plural": "Variações"},
        ),
    ]
