version: "3.9"


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    depends_on:
      - db
    
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loja

  # Opcional
  # pgadmin:
  #    image: dpage/pgadmin4
  #    container_name: pgadmin
  #    ports:
  #     - "5050:80"
  #    environment:
  #      PGADMIN_DEFAULT_EMAIL: email@example.com
  #      PGADMIN_DEFAULT_PASSWORD: password_example
  #    depends_on:
  #      - db

volumes:
  postgres_data: