# Generated by Django 5.1.6 on 2025-02-08 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ciente',
            new_name='Cliente',
        ),
    ]
